services:
  web:
    container_name: "LP_ShoppingList_API"
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=shopping_list
      - DB_USER=root
      - DB_PASSWORD=rootpassword
    volumes:
      - .:/var/www/html

  db:
    container_name: "LP_ShoppingList_DB"
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shopping_list
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  schemaFetcher:
    container_name: "LP_ShoppingList_SchemaFetcher"
    image: node:16
    working_dir: /opt/app/
    tty: true
    healthcheck:
      disable: true
    volumes:
      - ./schema_fetcher/:/opt/app/

volumes:
  mysql_data:
